### ISSUE TITLE
Dúvida 

### ISSUE THREAD

**Issue by ghost** [FundacaoLemann/qedu-hub#7]
Olá,

Não vi pelo código, vocês planejam implementar API nessa versão?

Grato,

**Comment by marcusesa** [comment]
Olá @JDias, em um primeiro momento iremos migrar a base de código legada para este novo projeto. Quais dados você acha que seria interessante disponibilizar em uma API pública através do QEdu?

**Comment by ghost** [comment]
Eu acredito que muitos  indicadores @marcusesa
Não temos dados.
Teve essa iniciativa http://educacao.dadosabertosbr.com/api
E essa https://github.com/inepdadosabertos/api
Do inep propriamente dito o pessoal fala mas eu nunca vi.
A aplicação para controle social e gestão democratica seria uma mão na roda, seja para sites como esse meu rascunho http://csustentaveis.sisdipe.com.br ou, melhor ainda, para alimentar um portal de transparência individual da escola.

Eu tenho outros pensamentos acerca de sistemas de ti para o sistema educacional, se tiver interesse, e não for problema, eu poderia estar compartilhando aqui alguns link (uns 10 ou 15) que acho relevante sobre o tema.

Grato pela atenção,

**Comment by marcusesa** [comment]
Obrigado pelo interesse @JDias.

Sinta-se a vontade para compartilhar nesta issue ou de maneira privada pelo email tech@qedu.org.br.

**Comment by ghost** [comment]
Olá @marcusesa é que não sei se é o escopo de vocês, então vou compartilhar 3 links (3 temas diferentes) se algum interessar eu elaboro, ok? (por mim público é melhor, quanto mais visibilidade mais chance de alguém se interessar)

o 1o é LOR(n) , aqui tem um exemplo, mas é proprietário:

https://youtu.be/cWHjh4ZblZ8

o 2o é um player interativo, tbm é proprietário mas são para dar referencia apenas:

https://youtu.be/R1PvbhyN9jc

e o 3 é um padrão subset do commom education data standards http://www.pesc.org/
(no mesmo tema um vídeo sobre um tipo de badgechain, eu acho)

https://youtu.be/EOQ3bRJHNfs

não sei se o pessoal do qedu tem interesse nessas coisas, mas minha ideia era projetar um ecossistema envolvendo esses temas, e ao fim e a cabo ter algo como um "prontuário medico eletrônico" educacional.

se continuarem a achar o tema interessante posso compartilhar mais uns 4 ou 5 links que são mais de código aberto, uma forma de poder se chegar a esses resultados, acho. (o pessoal da lemann já tem algumas iniciativas como o geekie games e o qedu provas, então talvez se interessem?)

**Comment by marcelioleal** [comment]
@JDias obrigado pelas referências! O Pesc é algo que não tínhamos no radar, mas pode ter algo interessante tanto pra o QEdu quanto pra o QEdu Provas e QEdu Dados. Realmente nossa visão em médio prazo é partir pra uma padronização cada vez maior.

**Comment by ghost** [comment]
Olá @marcelioleal o common education data standards é bem amplo (o pesc tem um "primo" para as escolas dentro do ceds)

Imagino que estão tbm. antenados com trilhas de aprendizagem, vou compartilhar mais 4 links, não são sobre padronizações que foi o que o sr se interessou (e tbm. me interessa muito) mas acho que talvez agregue.

https://frametrail.org

https://github.com/memex/trails-proposal

https://twinery.org (consegue entender pq esse?)

E por último, mas nesse acho que vcs estão acompanhando de perto

http://grapple.win.tue.nl/software/

que compartilho por causa da abordagem modular 

tem um site chamado fabrica de provas, que achei interessante mas não é sobre o que estou falando aqui.

Sds.

**Comment by ghost** [comment]
Ps: esse tem mais relação com o pesc (mas é uma abordagem que me parece anterior a utilização do blockchain)

http://www.studentclearinghouse.org

Eu até hoje não sei se a legislação daqui já permite troca eletronica de dados entre as instituições escolares.

**Comment by ghost** [comment]
Bom, era isso :)
Para visualizar o quanto ainda temos pela frente segue dois links que nada tem a ver com educação, mas demonstra infraestrutura 

https://youtu.be/2XOqsJh4Abg

E o tunneling da api por segurança (tipo uma vpn)

https://github.com/ria-ee/X-Road

Eu gostaria muito que a legislação de ead fosse alterada, acho equivocado a abordagem dos polos de apoios, vc tendo experiências como as da sylva prometric (um erro o inep não ter um forte braço digital) e do meetup ( https://www.p2pu.org/en/ ) abordagem mais interessantes podiam surgir.

Na Finlândia o demolanet está revendo tudo, aqui o pessoal fica protegendo a kroton (a uab é pífia)

**Comment by marcusesa** [comment]
Mais uma vez obrigado @JDias por compartilhar estas referências com a gente. Uma outra fonte de dados do QEdu que pode ser util para você é o QEdu Dados, caso tenha interesse solicite seu acesso em http://dados.qedu.org.br/.

**Comment by ghost** [comment]
Grato @marcusesa ,
Mas não acredito que vá me ajudar, como eu comentei me interesso pelos dados basicamente para gestão democrática e para controle social, eu poder acessar os dados por si não faz a mágica. 

Keep up the good work! :)

**Comment by ghost** [comment]
Rascunho do que conversei (gestão democratica)

https://www.sisdipe.com.br/i-educar/interno/inicio.php

https://github.com/JDias/i-educar

**Comment by marcusesa** [comment]
Obrigado @JDias .
